kind: pipeline
name: default

steps:
- name: restore-cache
  pull: default
  image: drillster/drone-volume-cache
  settings:
    mount:
      - ./node_modules
    restore: true
  volumes:
    - name: adcca6560fdc95b3debc
      path: /cache

- name: test
  image: timbru31/java-node:latest
  environment:
    CODACY_PROJECT_TOKEN:
      from_secret: codacy_project_token
  commands:
    - yarn install
    - yarn buildAll
    - yarn test
    - yarn pushCoverage

- name: push-client
  image: node:12
  environment:
    GIT_TOKEN:
      from_secret: git_token
  commands:
    - git config --global user.name "FI Drone CI"
    - git config --global user.email "fhj.drone@fruitice.fr"
    - cd oa-ts-axios
    - sed -i '/dist/d' ./.gitignore
    - yarn
    - yarn build
    - rm git_push.sh
    - cp ../scripts/git_push.sh .
    - sh git_push.sh f-hj booster-js-client
  when:
    branch: master
    event: push
    status: success

- name: rebuild-cache
  pull: default
  image: drillster/drone-volume-cache
  settings:
    mount:
      - ./node_modules
    rebuild: true
  volumes:
    - name: adcca6560fdc95b3debc
      path: /cache

- name: docker-push
  image: plugins/docker
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    PLUGIN_REPO: docker-registry.fruitice.fr/booster-back
    PLUGIN_REGISTRY: docker-registry.fruitice.fr
    PLUGIN_TAG: ${DRONE_COMMIT}
  privileged: true
  when:
    branch: master
    event: push
    status: success

- name: kube-push
  image: quay.io/honestbee/drone-kubernetes
  environment:
    KUBERNETES_SERVER:
      from_secret: kubernetes_server
    KUBERNETES_CERT:
      from_secret: kubernetes_cert
    KUBERNETES_TOKEN:
      from_secret: kubernetes_token
    PLUGIN_NAMESPACE: booster
    PLUGIN_DEPLOYMENT: booster-back
    PLUGIN_REPO: docker-registry.fruitice.fr/booster-back
    PLUGIN_CONTAINER: booster-back
    PLUGIN_TAG: ${DRONE_COMMIT}
  when:
    branch: master
    event: push
    status: success